version: '3.1'
services:
  mongo:
      image: mongo
      command: mongod --smallfiles
      ports:
        - "28018:27017"
      volumes:
        - /data/db:/data/db
      networks:
        - all
  web:
    build: .
    ports:
      - "80:3000"
    depends_on:
      - mongo
    networks:
      - all
    environment:
      - PORT=3000
      - MONGO_DB=mongodb://mongo/spb
    secrets:
      - CLIENT_ID
      - CLIENT_SECRET

networks:
  all:

secrets:
  CLIENT_ID:
    file: secrets/client_id.txt
  CLIENT_SECRET:
    file: secrets/client_secret.txt